# End to end QA for the AIM site. Serve docs/ on port 8766, then run: python3 tests/qa.py
import asyncio, json, os, sys, csv, io
from playwright.async_api import async_playwright
B = os.environ.get("AIM_QA_URL", "http://127.0.0.1:8766/")
SHOTS = os.environ.get("AIM_QA_SHOTS", "/tmp/claude-0/shots")
fails, errs = [], []
def ok(cond, msg):
    print(("PASS " if cond else "FAIL ") + msg)
    if not cond: fails.append(msg)

async def wait(pg, ms=250): await pg.wait_for_timeout(ms)

async def main():
    os.makedirs(SHOTS, exist_ok=True)
    async with async_playwright() as p:
        br = await p.chromium.launch()
        ctx = await br.new_context(viewport={"width": 1366, "height": 900}, accept_downloads=True)
        await ctx.grant_permissions(["clipboard-read", "clipboard-write"], origin=B.rstrip("/"))
        pg = await ctx.new_page()
        pg.on("pageerror", lambda e: errs.append(str(e)))
        S = lambda name: pg.screenshot(path=f"{SHOTS}/qa_{name}.png", full_page=True)
        body = lambda: pg.inner_text("body")

        # ---------- landing ----------
        await pg.goto(B); await wait(pg, 300)
        ok(await pg.locator("#intro").count() == 1, "intro plays on first visit")
        await pg.click("#skipIntro"); await wait(pg, 800)
        ok(await pg.locator("#intro").count() == 0, "intro can be skipped")
        v0 = await pg.inner_text("#cf")
        await pg.evaluate("document.getElementById('rent').value=3500;document.getElementById('rent').dispatchEvent(new Event('input'))")
        ok(v0 != await pg.inner_text("#cf"), "landing calculator responds")
        ok(await pg.locator("a[href='app.html#demo']").count() >= 3, "landing links to the live demo")
        ok(await pg.locator("a[href='demo.html']").count() >= 3, "landing links to get started")
        ok("Request a demo" not in await body(), "no stale request a demo wording on the landing page")

        # ---------- start screen ----------
        await pg.goto(B + "app.html"); await wait(pg, 300)
        ok("How do you want to start?" in await body(), "fresh visit shows the start screen")
        ok(await pg.locator(".choice").count() == 2, "start screen offers demo and setup")
        await S("start")

        # ---------- demo mode ----------
        await pg.click("button.choice[data-v=demo]"); await wait(pg, 400)
        ok(await pg.locator(".ribbon").count() == 1 and "demo mode" in (await pg.inner_text(".ribbon")).lower(), "demo mode shows its ribbon")
        ok(await pg.locator(".modesw button[data-v=demo][aria-pressed=true]").count() == 1, "mode switch shows Demo selected")
        ok(await pg.locator(".onb").count() == 0, "demo hides the setup checklist")
        ok("Debt payoff" in await body() and "Financial independence" in await body(), "dashboard shows planner cards")
        await S("demo_dash")

        await pg.goto(B + "app.html#opportunities"); await wait(pg)
        ok(await pg.locator("tr[data-go]").count() == 5, "demo has 5 opportunities")
        await pg.fill("#oppSearch", "laundromat"); await wait(pg, 400)
        ok(await pg.locator("tr[data-go]").count() == 1, "search filters to one result")
        ok(await pg.evaluate("document.activeElement.id") == "oppSearch", "search keeps focus while typing")
        await pg.fill("#oppSearch", ""); await wait(pg, 400)
        await pg.select_option("#oppSort", "name"); await wait(pg, 200)
        names = await pg.locator("tr[data-go] .oname b").all_inner_texts()
        ok(names == sorted(names), "sort by name works")
        await pg.click("button[data-v=Owned]"); await wait(pg, 150)
        ok(await pg.locator("tr[data-go]").count() == 1, "status filter works")
        await pg.click("button[data-v=All]")
        async with pg.expect_download() as dl:
            await pg.click("button[data-act=csv][data-v=opps]")
        rows = list(csv.reader(io.StringIO(open(await (await dl.value).path()).read())))
        ok(rows[0][0] == "Name" and len(rows) == 6, f"opportunities CSV has a header and 5 rows ({len(rows)})")

        await pg.click("button[data-act='new-opp']"); await pg.click(".types label:has(input[value=str])")
        await pg.click(".modal button[type=submit]"); await wait(pg, 150)
        ok("Give the analysis a name" in await pg.inner_text(".modal"), "new analysis asks for a name")
        await pg.fill("#nName", "Smoky Mountain Cabin"); await pg.fill("#nLoc", "Gatlinburg, TN"); await pg.click(".modal button[type=submit]"); await wait(pg, 400)
        ok(await pg.input_value("#oppName") == "Smoky Mountain Cabin", "new analysis created and opened")
        sc0 = await pg.eval_on_selector("#results .dial text", "e=>e.textContent")
        await pg.fill("#in-occupancy", "75"); await wait(pg, 400)
        sc1 = await pg.eval_on_selector("#results .dial text", "e=>e.textContent")
        ok(sc0 != sc1, f"score updates live ({sc0} to {sc1})")
        await pg.click("button[data-act=how-score]"); await wait(pg, 150)
        ok(await pg.locator(".modal").count() == 1, "score explanation opens")
        await pg.keyboard.press("Escape"); await wait(pg, 300)
        ok(await pg.locator(".modal").count() == 0, "Escape closes a dialog")
        ok(await pg.locator("text=Loan schedule").count() == 1, "loan schedule shows")
        await pg.click("button[data-act=all-years]"); await wait(pg, 150)
        ok(await pg.locator("text=Show first 10 years").count() == 1, "loan schedule expands to all years")
        await S("str_analysis")
        await pg.click("button[data-v=scenarios]"); await wait(pg, 200)
        ok(await pg.locator("text=Financing options").count() == 1, "financing options table shows")
        await pg.click("button[data-v=diligence]"); await wait(pg, 200)
        await pg.click("input[data-check='0']"); await wait(pg, 250)
        ok(await pg.is_checked("input[data-check='0']"), "checklist item stays checked after save")
        await pg.fill("#checkIn", "Call the county about permits"); await pg.press("#checkIn", "Enter"); await wait(pg, 200)
        ok(await pg.locator("text=Call the county about permits").count() == 1, "custom checklist item added")
        await pg.fill("#logIn", "Offer sent at $325,000"); await pg.press("#logIn", "Enter"); await wait(pg, 200)
        ok(await pg.locator(".timeline >> text=Offer sent at $325,000").count() == 1, "history note logged")
        await pg.select_option("#oppStatus", "Owned"); await wait(pg, 300)
        ok(await pg.locator("button[data-v=ownership]").count() == 1, "marking Owned adds the Ownership tab")
        await pg.click("button[data-v=ownership]"); await pg.click("button[data-act=add-actual]"); await wait(pg, 300)
        ok(await pg.locator("input[data-k=revenue]").count() == 1, "owned month logged")
        await pg.click("button[data-v=report]"); await wait(pg, 200)
        await pg.click("button[data-act=copy-report]"); await wait(pg, 300)
        clip = await pg.evaluate("navigator.clipboard.readText()")
        ok("AIM Score" in clip and "Smoky Mountain Cabin" in clip, "report summary copied")
        await pg.click("button[data-act=share]"); await wait(pg, 300)
        share = await pg.evaluate("navigator.clipboard.readText()")
        ok("#import=" in share, "share link copied")
        await S("report")
        await pg.click("button[data-act=del]"); await wait(pg, 300)
        ok("opportunities" in pg.url, "delete returns to the list")
        await pg.click(".toast button"); await wait(pg, 300)
        ok(await pg.input_value("#oppName") == "Smoky Mountain Cabin", "undo restores the deleted analysis")

        await pg.goto(B + "app.html#compare"); await wait(pg)
        ok(await pg.locator("td.best").count() >= 3, "compare highlights leaders")

        await pg.goto(B + "app.html#budget"); await wait(pg)
        ok("Where your money goes" in await body(), "budget shows the spending breakdown")
        first = pg.locator("input[data-line=income][data-k=amount]").first
        await first.fill("7000"); await first.press("Tab"); await wait(pg, 300)
        ok("$7,900" in await pg.locator(".kpi").first.inner_text(), "budget income total updates")
        g0 = await pg.locator("input[data-goal][data-k=name]").count()
        await pg.click("button[data-act=add-goal]"); await wait(pg, 200)
        ok(await pg.locator("input[data-goal][data-k=name]").count() == g0 + 1, "goal added")

        await pg.goto(B + "app.html#networth"); await wait(pg)
        before = await pg.inner_text(".kpi.hero strong")
        await pg.click("button[data-act=add-acct]"); await wait(pg, 200)
        last = pg.locator("input[data-acct][data-k=value]").last
        await last.fill("10000"); await last.press("Tab"); await wait(pg, 300)
        ok(before != await pg.inner_text(".kpi.hero strong"), "net worth updates with a new account")

        # planner
        await pg.goto(B + "app.html#planner"); await wait(pg)
        d0 = await pg.inner_text(".kpi.hero strong")
        await pg.fill("#pl-extra", "1000"); await pg.press("#pl-extra", "Tab"); await wait(pg, 300)
        d1 = await pg.inner_text(".kpi.hero strong")
        ok(d0 != d1, f"more extra payment moves the debt free date ({d0} to {d1})")
        await pg.click("button[data-act=plan-method][data-v=snowball]"); await wait(pg, 200)
        ok(await pg.locator("button[data-act=plan-method][data-v=snowball][aria-pressed=true]").count() == 1, "snowball method selects")
        ok("Credit card balance" in await pg.locator(".timeline li").first.inner_text(), "snowball pays the smallest balance first")
        await S("planner_debt")
        await pg.click("button[data-act=plan-tab][data-v=fi]"); await wait(pg, 900)
        y0 = await pg.locator(".kpi").nth(1).inner_text()
        await pg.fill("#pf-monthly", "5000"); await pg.press("#pf-monthly", "Tab"); await wait(pg, 300)
        y1 = await pg.locator(".kpi").nth(1).inner_text()
        ok(y0 != y1, "investing more changes the independence date")
        await pg.click("button[data-act=plan-reset]"); await wait(pg, 200)
        ok(await pg.locator(".kpi").nth(1).inner_text() == y0, "Use my numbers restores the defaults")
        await S("planner_fi")

        await pg.goto(B + "app.html#settings"); await wait(pg)
        await pg.fill("#s-coc", "12"); await pg.locator("#s-coc").press("Tab"); await wait(pg, 300)
        await pg.goto(B + "app.html#aimbot"); await wait(pg)
        await pg.fill("#botIn", "what should I offer"); await pg.press("#botIn", "Enter"); await wait(pg, 200)
        ok("12%" in await pg.locator(".msg.bot").last.inner_text(), "AIMBot uses the updated 12% target")
        await pg.click("button[data-act=ask][data-q='How do I pay off my debt?']"); await wait(pg, 200)
        ok("Avalanche" in await pg.locator(".msg.bot").last.inner_text(), "AIMBot answers debt questions")
        await pg.click("button[data-act=ask][data-q='When can I retire?']"); await wait(pg, 200)
        ok("independence number" in await pg.locator(".msg.bot").last.inner_text(), "AIMBot answers independence questions")

        # palette and shortcuts
        await pg.goto(B + "app.html#dashboard"); await wait(pg)
        await pg.keyboard.press("Control+k"); await wait(pg, 150)
        ok(await pg.locator("#palIn").count() == 1, "Ctrl K opens search")
        await pg.keyboard.type("gulf"); await wait(pg, 150); await pg.keyboard.press("Enter"); await wait(pg, 300)
        ok("opp-" in pg.url and await pg.input_value("#oppName") == "Gulf Breeze Condo", "search jumps to a deal")
        await pg.click("body", position={"x": 5, "y": 5}); await pg.keyboard.press("g"); await pg.keyboard.press("b"); await wait(pg, 250)
        ok(pg.url.endswith("#budget"), "g then b opens the budget")

        # reset demo
        await pg.goto(B + "app.html#settings"); await wait(pg)
        await pg.click("main button[data-act=ask-reset-demo]"); await pg.click("button[data-act=do-reset-demo]"); await wait(pg, 300)
        await pg.goto(B + "app.html#opportunities"); await wait(pg)
        ok(await pg.locator("tr[data-go]").count() == 5, "reset demo restores the sample portfolio")

        # ---------- get started and setup ----------
        await pg.goto(B + "demo.html"); await pg.click("#go"); await wait(pg, 150)
        ok(await pg.locator("[aria-invalid=true]").count() == 4, "get started form flags all 4 required fields")
        await pg.fill("#fname", "George"); await pg.fill("#lname", "Serafin"); await pg.fill("#email", "bad"); await pg.select_option("#role", index=2)
        await pg.click("#go"); await wait(pg, 100)
        ok(await pg.locator("#email[aria-invalid=true]").count() == 1, "form rejects a bad email")
        await pg.fill("#email", "george@example.com"); await pg.click("input[value='Business acquisitions']"); await pg.click("#go")
        await pg.wait_for_selector("#open")
        ok(await pg.locator("a[href='app.html#demo']").count() >= 1, "success offers the demo too")
        await pg.click("#open"); await wait(pg, 400)
        ok("step 1 of 5" in (await body()).lower(), "setup wizard opens")
        ok(await pg.input_value("#su-name") == "George", "setup prefills the first name")
        ok(await pg.is_checked("input[data-su-focus='Business acquisitions']"), "setup prefills interests")
        await pg.fill("#su-name", ""); await pg.click("#setupForm button[type=submit]"); await wait(pg, 150)
        ok("Enter your first name" in await body(), "setup requires a name")
        await pg.fill("#su-name", "George"); await pg.click("#setupForm button[type=submit]"); await wait(pg, 200)
        await pg.fill("#su-pay", "7200"); await pg.fill("#su-exp-housing", "2100"); await pg.fill("#su-exp-groceries", "600"); await wait(pg, 100)
        ok("$4,500" in await pg.inner_text("#suSum"), "setup shows live free cash flow")
        await pg.click("#setupForm button[type=submit]"); await wait(pg, 200)
        await pg.fill("#su-cash", "40000"); await pg.fill("#su-invest", "25000")
        await pg.locator("[data-sd][data-k=name]").first.fill("Car loan"); await pg.locator("[data-sd][data-k=balance]").first.fill("18000")
        await pg.locator("[data-sd][data-k=rate]").first.fill("6.5"); await pg.locator("[data-sd][data-k=min]").first.fill("390")
        await pg.click("button[data-act=su-add-debt]"); await wait(pg, 150)
        ok(await pg.input_value("[data-sd][data-k=balance] >> nth=0") == "18000", "adding a debt keeps typed values")
        await pg.click("#setupForm button[type=submit]"); await wait(pg, 200)
        await pg.click("button[data-act=su-preset][data-v=conservative]"); await wait(pg, 150)
        ok(await pg.input_value("#su-coc") == "10", "target preset fills the fields")
        await pg.click("#setupForm button[type=submit]"); await wait(pg, 900)
        rv = await body()
        ok("$47,000" in rv and "$4,500" in rv, "review shows net worth and free cash flow")
        await S("setup_review")
        await pg.click("input[data-su-first][value=rental]"); await pg.click("#setupForm button[type=submit]"); await wait(pg, 500)
        ok("opp-" in pg.url and await pg.input_value("#oppName") == "My first rental", "setup can start a first analysis")
        await pg.goto(B + "app.html#dashboard"); await wait(pg)
        ok("George" in await pg.inner_text("h1"), "live workspace greets by name")
        ok(await pg.locator(".ribbon").count() == 0, "live workspace has no demo ribbon")
        ok("3 of 5" in await body(), "setup completes three checklist steps")
        await pg.goto(B + "app.html#opportunities"); await wait(pg)
        ok(await pg.locator("tr[data-go]").count() == 1, "live workspace holds only its own deal")
        await pg.goto(B + "app.html#settings"); await wait(pg)
        ok(await pg.input_value("#s-coc") == "10", "live targets come from setup")
        await pg.click(".modesw button[data-v=demo]"); await wait(pg, 300)
        await pg.goto(B + "app.html#opportunities"); await wait(pg)
        ok(await pg.locator("tr[data-go]").count() == 5, "demo data is kept separate")
        await pg.click(".modesw button[data-v=live]"); await wait(pg, 300)
        ok("George" in await pg.inner_text("h1"), "switching back opens the live workspace")

        # share link import into live
        await pg.goto(share.replace("http://127.0.0.1:8766/", B)); await wait(pg, 400)
        ok("Open a shared analysis" in await body(), "share link offers an import")
        await pg.click("#doImport"); await wait(pg, 300)
        ok(await pg.input_value("#oppName") == "Smoky Mountain Cabin", "shared analysis imported")
        await pg.goto(B + "app.html#import=garbage"); await wait(pg, 300)
        ok("damaged" in await body(), "a broken share link is reported")

        # backup, erase, restore from start
        await pg.goto(B + "app.html#settings"); await wait(pg)
        async with pg.expect_download() as dl:
            await pg.click("button[data-act=backup-dl]")
        path = await (await dl.value).path(); data = json.load(open(path))
        ok(len(data["workspace"]["opps"]) == 2, "backup contains the live workspace")
        await pg.click("button[data-act=ask-erase]"); await pg.click("button[data-act=do-erase]"); await wait(pg, 300)
        ok("step 1 of 5" in (await body()).lower(), "erasing returns to setup")
        await pg.evaluate("localStorage.clear()"); await pg.goto(B + "app.html"); await pg.reload(); await wait(pg, 300)
        bad = os.path.join(SHOTS, "bad.json"); open(bad, "w").write('{"hello":1}')
        await pg.set_input_files("#startRestore", bad); await wait(pg, 300)
        ok("not an AIM backup" in await pg.inner_text("#restoreSlot"), "restore rejects a wrong file")
        await pg.set_input_files("#startRestore", path); await wait(pg, 300)
        await pg.click("button[data-act=do-restore]"); await wait(pg, 300)
        await pg.goto(B + "app.html#opportunities"); await wait(pg)
        ok(await pg.locator("tr[data-go]").count() == 2, "restore from the start screen brings back the workspace")
        await pg.reload(); await wait(pg, 300)
        ok(await pg.locator("tr[data-go]").count() == 2, "data persists after reload")

        # migration of an earlier beta workspace
        await pg.goto(B + "privacy.html")
        await pg.evaluate("localStorage.clear(); localStorage.setItem('aim.workspace.v1', JSON.stringify({v:1,sample:true,settings:{name:'Old',minDscr:1.25,minCoc:8,reserveMonths:6},budget:{income:[],expenses:[],goals:[]},accounts:[{id:'a',name:'Auto loan',type:'Liability',value:14800}],opps:[{id:'x',type:'rental',name:'Legacy Duplex',status:'Evaluating',inputs:{}}],history:[]}))")
        await pg.goto(B + "app.html#opportunities"); await wait(pg, 300)
        ok("Legacy Duplex" in await body() and await pg.locator(".ribbon").count() == 1, "earlier sample workspace moves to the demo")
        await pg.goto(B + "app.html#planner"); await wait(pg, 900)
        ok("6.90%" in await body(), "earlier sample loans get planner terms")

        for page in ["privacy.html", "terms.html", "404.html", "sitemap.xml", "robots.txt"]:
            r = await pg.goto(B + page); ok(r.status == 200, page + " loads")

        # ---------- phone ----------
        m = await br.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2); mp = await m.new_page()
        mp.on("pageerror", lambda e: errs.append("phone: " + str(e)))
        await mp.goto(B); await wait(mp, 200); await mp.click("#skipIntro"); await wait(mp, 700)
        await mp.click("#menuBtn"); await wait(mp, 150)
        ok(await mp.is_visible("#mnav"), "phone menu opens")
        await mp.click("#mnav a[href='#faq']"); await wait(mp, 200)
        ok(not await mp.is_visible("#mnav"), "phone menu closes after a link")
        for u in ["app.html", "app.html#setup"]:
            await mp.goto(B + u); await wait(mp, 300)
            w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth")
            ok(w <= 0, f"phone {u} has no sideways scroll ({w})")
            await mp.screenshot(path=f"{SHOTS}/qa_m_{u.replace('#','_')}.png", full_page=True)
        await mp.goto(B + "app.html#demo"); await wait(mp, 300)
        for v in ["dashboard", "opportunities", "compare", "budget", "networth", "planner", "aimbot", "learn", "settings"]:
            await mp.goto(B + "app.html#" + v); await wait(mp, 250)
            w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth")
            ok(w <= 0, f"phone {v} has no sideways scroll ({w})")
            await mp.screenshot(path=f"{SHOTS}/qa_m_{v}.png", full_page=True)
        await mp.goto(B + "app.html#planner"); await wait(mp, 200); await mp.click("button[data-act=plan-tab][data-v=fi]"); await wait(mp, 250)
        w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth"); ok(w <= 0, f"phone independence planner has no sideways scroll ({w})")
        await mp.goto(B + "app.html#opportunities"); await wait(mp, 200)
        await mp.locator("tr[data-go]").first.click(); await wait(mp, 300)
        for t in ["analysis", "scenarios", "diligence", "report"]:
            btn = mp.locator(f"button[data-v={t}]")
            if await btn.count(): await btn.click(); await wait(mp, 200)
            w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth")
            ok(w <= 0, f"phone {t} tab has no sideways scroll ({w})")
        await br.close()
    print("\nPAGE ERRORS:", errs or "none")
    print("FAILED:", len(fails), fails)
    sys.exit(1 if fails or errs else 0)

asyncio.run(main())
