# End to end QA for the AIM site. Serve docs/ on port 8766, then run: python3 tests/qa.py
import asyncio, json, os, sys
from playwright.async_api import async_playwright
B = os.environ.get("AIM_QA_URL", "http://127.0.0.1:8766/")
SHOTS = os.environ.get("AIM_QA_SHOTS", "/tmp/claude-0/shots")
fails, errs = [], []
def ok(cond, msg):
    print(("PASS " if cond else "FAIL ") + msg)
    if not cond: fails.append(msg)

async def main():
    os.makedirs(SHOTS, exist_ok=True)
    async with async_playwright() as p:
        br = await p.chromium.launch()
        ctx = await br.new_context(viewport={"width": 1366, "height": 900})
        await ctx.grant_permissions(["clipboard-read", "clipboard-write"], origin=B.rstrip("/"))
        pg = await ctx.new_page()
        pg.on("pageerror", lambda e: errs.append(str(e)))
        S = lambda name: pg.screenshot(path=f"{SHOTS}/qa_{name}.png", full_page=True)

        await pg.goto(B); await pg.wait_for_timeout(300)
        ok(await pg.locator("#intro").count() == 1, "intro plays on first visit")
        await pg.click("#skipIntro"); await pg.wait_for_timeout(800)
        ok(await pg.locator("#intro").count() == 0, "intro can be skipped")
        v0 = await pg.inner_text("#cf")
        await pg.evaluate("document.getElementById('rent').value=3500;document.getElementById('rent').dispatchEvent(new Event('input'))")
        v1 = await pg.inner_text("#cf")
        ok(v0 != v1, f"landing calculator responds ({v0} to {v1})")
        await pg.goto(B + "app.html"); await pg.wait_for_timeout(300)
        ok("Request a demo to open AIM" in await pg.inner_text("body"), "app is gated before a demo request")

        await pg.goto(B + "demo.html"); await pg.click("#go"); await pg.wait_for_timeout(150)
        ok(await pg.locator("[aria-invalid=true]").count() == 4, "demo form flags all 4 required fields")
        await pg.fill("#fname", "George"); await pg.fill("#lname", "Serafin"); await pg.fill("#email", "bad"); await pg.select_option("#role", index=2)
        await pg.click("#go"); await pg.wait_for_timeout(100)
        ok(await pg.locator("#email[aria-invalid=true]").count() == 1, "demo form rejects a bad email")
        await pg.fill("#email", "george@example.com"); await pg.click("input[value='Business acquisitions']"); await pg.click("#go")
        await pg.wait_for_selector("#open"); await pg.click("#open"); await pg.wait_for_timeout(500)
        h1 = await pg.inner_text("h1")
        ok("Good" in h1 and "George" in h1, "demo opens the app greeting by first name")
        ok(await pg.locator(".onb .step").count() == 5, "getting started checklist shows 5 steps")
        await S("dash")

        await pg.goto(B + "app.html#opportunities"); await pg.wait_for_timeout(200)
        n_all = await pg.locator("tr[data-go]").count()
        ok(n_all == 5, "sample has 5 opportunities")
        await pg.fill("#oppSearch", "laundromat"); await pg.wait_for_timeout(400)
        ok(await pg.locator("tr[data-go]").count() == 1, "search filters to one result")
        ok(await pg.evaluate("document.activeElement.id") == "oppSearch", "search keeps focus while typing")
        await pg.fill("#oppSearch", ""); await pg.wait_for_timeout(400)
        await pg.select_option("#oppSort", "name"); await pg.wait_for_timeout(200)
        names = await pg.locator("tr[data-go] .oname b").all_inner_texts()
        ok(names == sorted(names), "sort by name works")
        await pg.click("button[data-v=Owned]"); await pg.wait_for_timeout(150)
        ok(await pg.locator("tr[data-go]").count() == 1, "status filter works")
        await pg.click("button[data-v=All]")

        await pg.click("button[data-act='new-opp']"); await pg.click(".types label:has(input[value=str])")
        await pg.fill("#nName", "Smoky Mountain Cabin"); await pg.fill("#nLoc", "Gatlinburg, TN"); await pg.click(".modal button[type=submit]"); await pg.wait_for_timeout(400)
        ok(await pg.input_value("#oppName") == "Smoky Mountain Cabin", "new analysis created and opened")
        sc0 = await pg.eval_on_selector("#results .dial text", "e=>e.textContent")
        await pg.fill("#in-occupancy", "75"); await pg.wait_for_timeout(400)
        sc1 = await pg.eval_on_selector("#results .dial text", "e=>e.textContent")
        ok(sc0 != sc1, f"score updates live ({sc0} to {sc1})")
        await pg.click("button[data-act=how-score]"); await pg.wait_for_timeout(150)
        ok(await pg.locator(".modal").count() == 1, "score explanation opens")
        await pg.click(".modal footer .btn"); await pg.wait_for_timeout(100)
        ok(await pg.locator("text=Loan schedule").count() == 1, "loan schedule shows")
        await pg.click("button[data-act=all-years]"); await pg.wait_for_timeout(150)
        ok(await pg.locator("text=Show first 10 years").count() == 1, "loan schedule expands to all years")
        await S("str_analysis")
        await pg.click("button[data-v=scenarios]"); await pg.wait_for_timeout(200)
        ok(await pg.locator("text=Financing options").count() == 1, "financing options table shows"); await S("scenarios")
        await pg.click("button[data-v=diligence]"); await pg.wait_for_timeout(200)
        await pg.click("input[data-check='0']"); await pg.wait_for_timeout(250)
        ok(await pg.is_checked("input[data-check='0']"), "checklist item stays checked after save")
        await pg.fill("#checkIn", "Call the county about permits"); await pg.press("#checkIn", "Enter"); await pg.wait_for_timeout(200)
        ok(await pg.locator("text=Call the county about permits").count() == 1, "custom checklist item added")
        await pg.fill("#logIn", "Offer sent at $325,000"); await pg.press("#logIn", "Enter"); await pg.wait_for_timeout(200)
        ok(await pg.locator(".timeline >> text=Offer sent at $325,000").count() == 1, "history note logged")
        await pg.select_option("#oppStatus", "Owned"); await pg.wait_for_timeout(300)
        ok(await pg.locator("button[data-v=ownership]").count() == 1, "marking Owned adds the Ownership tab")
        await pg.click("button[data-v=diligence]"); await pg.wait_for_timeout(200)
        ok(await pg.locator(".timeline >> text=Marked as Owned").count() == 1, "status change recorded in history"); await S("diligence")
        await pg.click("button[data-v=ownership]"); await pg.click("button[data-act=add-actual]"); await pg.wait_for_timeout(300)
        ok(await pg.locator("input[data-k=revenue]").count() == 1, "owned month logged")
        await pg.click("button[data-v=report]"); await pg.wait_for_timeout(200)
        ok(await pg.locator("button[data-act=print]").count() == 1, "print button shows on the live site")
        await pg.click("button[data-act=copy-report]"); await pg.wait_for_timeout(300)
        clip = await pg.evaluate("navigator.clipboard.readText()")
        ok("AIM Score" in clip and "Smoky Mountain Cabin" in clip, "report summary copied to clipboard"); await S("report")

        await pg.click("button[data-act=del]"); await pg.wait_for_timeout(300)
        ok("opportunities" in pg.url, "delete returns to the list")
        await pg.click(".toast button"); await pg.wait_for_timeout(300)
        ok(await pg.input_value("#oppName") == "Smoky Mountain Cabin", "undo restores the deleted analysis")

        await pg.goto(B + "app.html#compare"); await pg.wait_for_timeout(250)
        ok(await pg.locator("td.best").count() >= 3, "compare highlights leaders"); await S("compare")

        await pg.goto(B + "app.html#budget"); await pg.wait_for_timeout(200)
        first = pg.locator("input[data-line=income][data-k=amount]").first
        await first.fill("7000"); await first.press("Tab"); await pg.wait_for_timeout(300)
        ok("$7,900" in await pg.locator(".kpi").first.inner_text(), "budget income total updates")
        g0 = await pg.locator("input[data-goal][data-k=name]").count()
        await pg.click("button[data-act=add-goal]"); await pg.wait_for_timeout(200)
        ok(await pg.locator("input[data-goal][data-k=name]").count() == g0 + 1, "goal added")

        await pg.goto(B + "app.html#networth"); await pg.wait_for_timeout(200)
        before = await pg.inner_text(".kpi.hero strong")
        await pg.click("button[data-act=add-acct]"); await pg.wait_for_timeout(200)
        last = pg.locator("input[data-acct][data-k=value]").last
        await last.fill("10000"); await last.press("Tab"); await pg.wait_for_timeout(300)
        after = await pg.inner_text(".kpi.hero strong")
        ok(before != after, f"net worth updates with a new account ({before} to {after})")
        await pg.click("button[data-act=snapshot]"); await pg.wait_for_timeout(200); await S("networth")

        await pg.goto(B + "app.html#settings"); await pg.wait_for_timeout(200)
        await pg.fill("#s-coc", "12"); await pg.locator("#s-coc").press("Tab"); await pg.wait_for_timeout(300)
        await pg.goto(B + "app.html#aimbot"); await pg.wait_for_timeout(200)
        await pg.fill("#botIn", "what should I offer"); await pg.press("#botIn", "Enter"); await pg.wait_for_timeout(200)
        ok("12%" in await pg.locator(".msg.bot").last.inner_text(), "AIMBot uses the updated 12% target")
        await pg.goto(B + "app.html#learn"); await pg.wait_for_timeout(200)
        await pg.locator("button.lesson").nth(4).click(); await pg.click("button[data-act=lesson-done]"); await pg.wait_for_timeout(200)
        await pg.goto(B + "app.html#dashboard"); await pg.wait_for_timeout(300)
        ok(await pg.locator(".onb").count() == 0, "getting started card completes and goes away")

        await pg.goto(B + "app.html#settings"); await pg.wait_for_timeout(200)
        async with pg.expect_download() as dl:
            await pg.click("button[data-act=backup-dl]")
        path = await (await dl.value).path(); data = json.load(open(path))
        ok(any(o["name"] == "Smoky Mountain Cabin" for o in data["workspace"]["opps"]), "backup file contains the workspace")
        await pg.click("button[data-act=ask-reset][data-v=empty]"); await pg.click("button[data-act=do-reset]"); await pg.wait_for_timeout(300)
        ok("No deals in progress" in await pg.inner_text("body"), "empty workspace shows empty states"); await S("empty")
        await pg.goto(B + "app.html#settings"); await pg.wait_for_timeout(200)
        await pg.set_input_files("#restoreFile", path); await pg.wait_for_timeout(300)
        await pg.click("button[data-act=do-restore]"); await pg.wait_for_timeout(300)
        await pg.goto(B + "app.html#opportunities"); await pg.wait_for_timeout(200)
        ok(await pg.locator("tr[data-go]").count() == 6, "restore brings back all 6 opportunities")
        bad = os.path.join(SHOTS, "bad.json"); open(bad, "w").write('{"hello":1}')
        await pg.goto(B + "app.html#settings"); await pg.wait_for_timeout(200)
        await pg.set_input_files("#restoreFile", bad); await pg.wait_for_timeout(300)
        ok("not an AIM backup" in await pg.inner_text("#restoreSlot"), "restore rejects a wrong file")
        await pg.reload(); await pg.goto(B + "app.html#opportunities"); await pg.wait_for_timeout(300)
        ok(await pg.locator("tr[data-go]").count() == 6, "data persists after reload")
        for page in ["privacy.html", "terms.html", "404.html", "sitemap.xml", "robots.txt"]:
            r = await pg.goto(B + page); ok(r.status == 200, page + " loads")

        m = await br.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2); mp = await m.new_page()
        mp.on("pageerror", lambda e: errs.append("phone: " + str(e)))
        await mp.goto(B); await mp.wait_for_timeout(200); await mp.click("#skipIntro"); await mp.wait_for_timeout(700)
        await mp.click("#menuBtn"); await mp.wait_for_timeout(150)
        ok(await mp.is_visible("#mnav"), "phone menu opens"); await mp.screenshot(path=f"{SHOTS}/qa_m_menu.png")
        await mp.click("#mnav a[href='#faq']"); await mp.wait_for_timeout(200)
        ok(not await mp.is_visible("#mnav"), "phone menu closes after a link")
        await mp.goto(B + "app.html#welcome"); await mp.wait_for_timeout(300)
        for v in ["dashboard", "opportunities", "compare", "budget", "networth", "aimbot", "learn", "settings"]:
            await mp.goto(B + "app.html#" + v); await mp.wait_for_timeout(250)
            w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth")
            ok(w <= 0, f"phone {v} has no sideways scroll ({w})")
        await mp.goto(B + "app.html#opportunities"); await mp.wait_for_timeout(200)
        await mp.locator("tr[data-go]").first.click(); await mp.wait_for_timeout(300)
        for t in ["analysis", "scenarios", "diligence", "report"]:
            btn = mp.locator(f"button[data-v={t}]")
            if await btn.count(): await btn.click(); await mp.wait_for_timeout(200)
            w = await mp.evaluate("document.documentElement.scrollWidth - innerWidth")
            ok(w <= 0, f"phone {t} tab has no sideways scroll ({w})")
            await mp.screenshot(path=f"{SHOTS}/qa_m_{t}.png", full_page=True)
        await br.close()
    print("\nPAGE ERRORS:", errs or "none")
    print("FAILED:", len(fails), fails)
    sys.exit(1 if fails or errs else 0)

asyncio.run(main())
